version: '3'

services:
  postgres-workout-db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - ./init_scripts/01_ddl.sql:/docker-entrypoint-initdb.d/01_ddl.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 2s
      retries: 10

  workout-service:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:3000/actuator/health" ]
      interval: 5s
      timeout: 2s
      retries: 10
    depends_on:
      postgres-workout-db:
        condition: service_healthy